column_width = 120
indent_type = "Spaces"
indent_width = 2
collapse_simple_statement = "FunctionOnly"
block_newline_gaps = "Preserve"
                                                                                                                         
